fix: font style fixed
varun-singhh/vovoca pull request #72
Opened 2021-10-11 10:10 UTC by SourabhKanade

Now font looks good.

![image](https://user-images.githubusercontent.com/80252410/136772284-be08ff2a-d1be-4547-9325-5e43bcf3b915.png)

2021-10-11 13:56 UTC, kaustubhai requested changes
Also please remove `package.json` and `package-lock.json` in your commits

2021-10-11 13:56 UTC, kaustubhai commented on components/homepage/Footer/Footer.jsx
> +                    fontSize: "15px",
Why have you choose inline styling here when you have done similar thing in the CSS as well?
Also, please go through the CONTRIBUTING.md once before committing changes again

2021-10-11 14:32 UTC, SourabhKanade commented on components/homepage/Footer/Footer.jsx
> +                    fontSize: "15px",
Okay

2021-10-11 18:50 UTC, kaustubhai requested changes
You deleted `package.json` and `package-lock.json`, if I'l merge this as it is, I'll lose these files. Please instead of deleting, restore to them as in the last merged commit

2021-10-11 18:50 UTC, kaustubhai commented on .gitignore
> +/package.json
what if someone actually uses a new package in the code, this can't be here

2021-10-11 19:02 UTC, SourabhKanade commented
@kaustubhai I hope now everything is okay?

2021-10-11 19:11 UTC, kaustubhai commented
>  Please instead of deleting, restore to them as in the last merged commit
I will still lose my `package.json` and `package-lock.json`

You should restore them to thier last correct version

2021-10-13 14:49 UTC, merged

2021-10-13 14:56 UTC, kaustubhai commented
@SourabhKanade can you please share Issue number here, thanks.

2021-10-13 15:06 UTC, SourabhKanade commented
> @SourabhKanade can you please share Issue number here, thanks.

Hello @kaustubhai this was issue number #63 
THANKS 👍